[theme]
primaryColor="#0168b1"
backgroundColor="#f5f7f9"
secondaryBackgroundColor="#e0e5ec"
textColor="#262730"
font="sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = true