project:
  type: website

website:
  page-navigation: true
  title: "Reproduce to Learn"
  description: "Reproduce To Learn."
  site-url: "https://datasciencebox.org/"

  page-footer:
    left: "This page is built with ❤️."
    background: "#000000"
    right:
    - text: "License"
      # href: LICENSE.md
    - text: "Code of Conduct"
      # href: CODE_OF_CONDUCT.md

  navbar:
    background: "#000000"
    align: center
    title: false
    collapse-below: lg

    right:
      - icon: github
        href: https://github.com/rstudio-education/datascience-box
        aria-label: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/1655/join?access_code=5rdjusfIYF5iI0Gum2vNsBDLdtdnIEELBkf2EivK
        aria-label: RStudio Cloud

    left:
      - text: "Reproduce to Learn"
        href: index.qmd
      - text: "Mental Model"
        href: mental_models/01_mental_model.qmd
      - text: "Data Viz"
        href: data_viz/01_how_popular_binden.qmd

  sidebar:
    - id: mental_models
      title: "Mental Models"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: mental_models/01_mental_model.qmd

    - id: data_viz
      title: "Data Viz"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: data_viz/01_how_popular_binden.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    code-fold: true
    embed-resources: true
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    mainfont: Inter
    # include-in-header: "style/fontawesome.html"
    grid:
      sidebar-width: 250px
      body-width: 1600px
      margin-width: 250px
      gutter-width: 1.5rem